added welcome page but i want to crate smaller components so it wont …
R123NLL/site_coupon_springboot pull request #35
Opened 2024-10-06 17:11 UTC by R123NLL

…be so crowded

2024-10-06 17:12 UTC, R123NLL commented
also needed to make each purchase reducing inventory amount and increasing amount in customer inventory

2024-10-10 11:01 UTC, VegasDevApps requested changes

2024-10-10 11:01 UTC, VegasDevApps commented on client/src/state/CouponInitialState.js
Ты не можешь поставить это в папку state.
 Папка state которая находиться в руте, он обычно для глобального состояния, которое имеет доступ по всему приложению. 
 
Это локальный state и по идеи должен быть доступен в одном компоненте. Если state нужен в нескольких компонентах, то надо использовать Redux или Mobix.

2024-10-10 11:01 UTC, VegasDevApps commented on backend/src/main/java/src/springboot/service/impl/CustomerServiceImpl.java
>                  .orElseThrow(() -> new IllegalArgumentException("Customer not found"));
У тебя тут неправильное исключение. Аргументы пришли правильные, но ты по ним ничего не нашел.

2024-10-10 11:01 UTC, VegasDevApps commented on backend/src/main/java/src/springboot/service/impl/CustomerServiceImpl.java
>                  .orElseThrow(() -> new IllegalArgumentException("Coupon not found"));
У тебя тут неправильное исключение. Аргументы пришли правильные, но ты по ним ничего не нашел.

2024-10-10 11:01 UTC, VegasDevApps commented on backend/src/main/java/src/springboot/service/impl/CustomerServiceImpl.java
> +        customerRepository.save(customer);
Сначала надо сохранить купон.

Т.к. у тебя в БД есть констрейт на количество купонов, надо обернуть сохранение coupon и customerRepository в try/catch.

ты конечно проверил наличие купонов, но следующий момент другой пользователь может купить все купоны и тогда будет исключение

2024-10-10 11:01 UTC, VegasDevApps commented on client/src/components/Coupon/CouponComponent.jsx
> +                    <div className="mt-2">
Как это выглядит на странице customer page?

2024-10-10 11:01 UTC, VegasDevApps commented on client/src/components/Coupon/CouponList.js
> +const CouponList = ({ coupons, handlePurchase }) => {
Т.к. файл находится в папке компонента, он может использоваться с другим целями и функциональностью, в этом и есть смысл компонентного программирования.

handlePurchase - слишком специфическое имя проперти. Назови onClickFunction

2024-10-10 11:01 UTC, VegasDevApps commented on client/src/components/Coupon/CouponList.js
> +                        btnClass={"primary"}
Т.к. файл находится в папке компонента, он может использоваться с другим целями и функциональностью, в этом и есть смысл компонентного программирования.
btnClass & btnText должен передаваться через пропсы

2024-10-10 11:01 UTC, VegasDevApps commented on client/src/components/Coupon/CouponList.js
файл возвращает jsx, должен иметь раcширение jsx

2024-10-10 11:01 UTC, VegasDevApps commented on client/src/pages/WelcomePage.jsx
> +            <WelcomeHeader />
на мой взгляд компонент WelcomeHeader излишне . Можно просто вставить сюда его содержимое. Он не выполняет никакой логики и нигде больше не используется, не заслуживает быть отдельным компонентом.

2024-10-11 08:35 UTC, VegasDevApps approved these changes

2024-10-11 08:36 UTC, merged